well_commerce_media:
    configuration:
        media:
            orm:
                factory: WellCommerce\Bundle\MediaBundle\Factory\MediaFactory
                repository: WellCommerce\Bundle\MediaBundle\Repository\MediaRepository
                mapping: "@WellCommerceMediaBundle/Resources/config/doctrine/Media.orm.yml"
                entity: WellCommerce\Bundle\MediaBundle\Entity\Media
            api:
                exposed: true
                dataset: media.dataset.admin
                manager: media.manager

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web/media/images"
    filter_sets:
        smallest:
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        small:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        normal:
            filters:
                thumbnail: { size: [175, 175], mode: outbound }
        medium:
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
        large:
            filters:
                thumbnail: { size: [600, 600], mode: outbound }
        largest:
            filters:
                thumbnail: { size: [1200, 1200], mode: outbound }
        original:
            filters:
              strip: ~
